// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/okadatakuya/my_folder/dev/my_app/badminist/backend/domain/community.go

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
	domain "github.com/takuya-okada-01/badminist-backend/domain"
)

// MockICommunityRepository is a mock of ICommunityRepository interface.
type MockICommunityRepository struct {
	ctrl     *gomock.Controller
	recorder *MockICommunityRepositoryMockRecorder
}

// MockICommunityRepositoryMockRecorder is the mock recorder for MockICommunityRepository.
type MockICommunityRepositoryMockRecorder struct {
	mock *MockICommunityRepository
}

// NewMockICommunityRepository creates a new mock instance.
func NewMockICommunityRepository(ctrl *gomock.Controller) *MockICommunityRepository {
	mock := &MockICommunityRepository{ctrl: ctrl}
	mock.recorder = &MockICommunityRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICommunityRepository) EXPECT() *MockICommunityRepositoryMockRecorder {
	return m.recorder
}

// DeleteCommunity mocks base method.
func (m *MockICommunityRepository) DeleteCommunity(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCommunity", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCommunity indicates an expected call of DeleteCommunity.
func (mr *MockICommunityRepositoryMockRecorder) DeleteCommunity(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCommunity", reflect.TypeOf((*MockICommunityRepository)(nil).DeleteCommunity), id)
}

// InsertCommunity mocks base method.
func (m *MockICommunityRepository) InsertCommunity(community *domain.Community) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertCommunity", community)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertCommunity indicates an expected call of InsertCommunity.
func (mr *MockICommunityRepositoryMockRecorder) InsertCommunity(community interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertCommunity", reflect.TypeOf((*MockICommunityRepository)(nil).InsertCommunity), community)
}

// SelectCommunitiesByUserID mocks base method.
func (m *MockICommunityRepository) SelectCommunitiesByUserID(userID string) ([]domain.Community, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectCommunitiesByUserID", userID)
	ret0, _ := ret[0].([]domain.Community)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectCommunitiesByUserID indicates an expected call of SelectCommunitiesByUserID.
func (mr *MockICommunityRepositoryMockRecorder) SelectCommunitiesByUserID(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectCommunitiesByUserID", reflect.TypeOf((*MockICommunityRepository)(nil).SelectCommunitiesByUserID), userID)
}

// SelectCommunity mocks base method.
func (m *MockICommunityRepository) SelectCommunity(id string) (domain.Community, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectCommunity", id)
	ret0, _ := ret[0].(domain.Community)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectCommunity indicates an expected call of SelectCommunity.
func (mr *MockICommunityRepositoryMockRecorder) SelectCommunity(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectCommunity", reflect.TypeOf((*MockICommunityRepository)(nil).SelectCommunity), id)
}

// UpdateCommunity mocks base method.
func (m *MockICommunityRepository) UpdateCommunity(community *domain.Community) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCommunity", community)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCommunity indicates an expected call of UpdateCommunity.
func (mr *MockICommunityRepositoryMockRecorder) UpdateCommunity(community interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCommunity", reflect.TypeOf((*MockICommunityRepository)(nil).UpdateCommunity), community)
}

// MockICommunityUseCase is a mock of ICommunityUseCase interface.
type MockICommunityUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockICommunityUseCaseMockRecorder
}

// MockICommunityUseCaseMockRecorder is the mock recorder for MockICommunityUseCase.
type MockICommunityUseCaseMockRecorder struct {
	mock *MockICommunityUseCase
}

// NewMockICommunityUseCase creates a new mock instance.
func NewMockICommunityUseCase(ctrl *gomock.Controller) *MockICommunityUseCase {
	mock := &MockICommunityUseCase{ctrl: ctrl}
	mock.recorder = &MockICommunityUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICommunityUseCase) EXPECT() *MockICommunityUseCaseMockRecorder {
	return m.recorder
}

// DeleteCommunity mocks base method.
func (m *MockICommunityUseCase) DeleteCommunity(ctx *gin.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCommunity", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCommunity indicates an expected call of DeleteCommunity.
func (mr *MockICommunityUseCaseMockRecorder) DeleteCommunity(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCommunity", reflect.TypeOf((*MockICommunityUseCase)(nil).DeleteCommunity), ctx, id)
}

// InsertCommunity mocks base method.
func (m *MockICommunityUseCase) InsertCommunity(ctx *gin.Context, userID string, community domain.Community) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertCommunity", ctx, userID, community)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertCommunity indicates an expected call of InsertCommunity.
func (mr *MockICommunityUseCaseMockRecorder) InsertCommunity(ctx, userID, community interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertCommunity", reflect.TypeOf((*MockICommunityUseCase)(nil).InsertCommunity), ctx, userID, community)
}

// SelectCommunitiesByUserID mocks base method.
func (m *MockICommunityUseCase) SelectCommunitiesByUserID(ctx *gin.Context, userID string) ([]domain.Community, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectCommunitiesByUserID", ctx, userID)
	ret0, _ := ret[0].([]domain.Community)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectCommunitiesByUserID indicates an expected call of SelectCommunitiesByUserID.
func (mr *MockICommunityUseCaseMockRecorder) SelectCommunitiesByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectCommunitiesByUserID", reflect.TypeOf((*MockICommunityUseCase)(nil).SelectCommunitiesByUserID), ctx, userID)
}

// SelectCommunity mocks base method.
func (m *MockICommunityUseCase) SelectCommunity(ctx *gin.Context, id string) (domain.Community, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectCommunity", ctx, id)
	ret0, _ := ret[0].(domain.Community)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectCommunity indicates an expected call of SelectCommunity.
func (mr *MockICommunityUseCaseMockRecorder) SelectCommunity(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectCommunity", reflect.TypeOf((*MockICommunityUseCase)(nil).SelectCommunity), ctx, id)
}

// UpdateCommunity mocks base method.
func (m *MockICommunityUseCase) UpdateCommunity(ctx *gin.Context, userID string, community *domain.Community) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCommunity", ctx, userID, community)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCommunity indicates an expected call of UpdateCommunity.
func (mr *MockICommunityUseCaseMockRecorder) UpdateCommunity(ctx, userID, community interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCommunity", reflect.TypeOf((*MockICommunityUseCase)(nil).UpdateCommunity), ctx, userID, community)
}
