// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/okadatakuya/my_folder/dev/00_app/badminist/backend/domain/owner.go

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/takuya-okada-01/badminist-backend/domain"
)

// MockIOwnerRepository is a mock of IOwnerRepository interface.
type MockIOwnerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIOwnerRepositoryMockRecorder
}

// MockIOwnerRepositoryMockRecorder is the mock recorder for MockIOwnerRepository.
type MockIOwnerRepositoryMockRecorder struct {
	mock *MockIOwnerRepository
}

// NewMockIOwnerRepository creates a new mock instance.
func NewMockIOwnerRepository(ctrl *gomock.Controller) *MockIOwnerRepository {
	mock := &MockIOwnerRepository{ctrl: ctrl}
	mock.recorder = &MockIOwnerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIOwnerRepository) EXPECT() *MockIOwnerRepositoryMockRecorder {
	return m.recorder
}

// DeleteOwner mocks base method.
func (m *MockIOwnerRepository) DeleteOwner(userID, communityID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOwner", userID, communityID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOwner indicates an expected call of DeleteOwner.
func (mr *MockIOwnerRepositoryMockRecorder) DeleteOwner(userID, communityID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOwner", reflect.TypeOf((*MockIOwnerRepository)(nil).DeleteOwner), userID, communityID)
}

// InsertOwner mocks base method.
func (m *MockIOwnerRepository) InsertOwner(owner domain.Owner) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOwner", owner)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertOwner indicates an expected call of InsertOwner.
func (mr *MockIOwnerRepositoryMockRecorder) InsertOwner(owner interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOwner", reflect.TypeOf((*MockIOwnerRepository)(nil).InsertOwner), owner)
}

// SelectOwnerByUserIDAndCommunityID mocks base method.
func (m *MockIOwnerRepository) SelectOwnerByUserIDAndCommunityID(userID, communityID string) (domain.Owner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectOwnerByUserIDAndCommunityID", userID, communityID)
	ret0, _ := ret[0].(domain.Owner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectOwnerByUserIDAndCommunityID indicates an expected call of SelectOwnerByUserIDAndCommunityID.
func (mr *MockIOwnerRepositoryMockRecorder) SelectOwnerByUserIDAndCommunityID(userID, communityID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectOwnerByUserIDAndCommunityID", reflect.TypeOf((*MockIOwnerRepository)(nil).SelectOwnerByUserIDAndCommunityID), userID, communityID)
}

// SelectOwnersByCommunityID mocks base method.
func (m *MockIOwnerRepository) SelectOwnersByCommunityID(communityID string) ([]domain.Owner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectOwnersByCommunityID", communityID)
	ret0, _ := ret[0].([]domain.Owner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectOwnersByCommunityID indicates an expected call of SelectOwnersByCommunityID.
func (mr *MockIOwnerRepositoryMockRecorder) SelectOwnersByCommunityID(communityID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectOwnersByCommunityID", reflect.TypeOf((*MockIOwnerRepository)(nil).SelectOwnersByCommunityID), communityID)
}

// SelectOwnersByUserID mocks base method.
func (m *MockIOwnerRepository) SelectOwnersByUserID(userID string) ([]domain.Owner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectOwnersByUserID", userID)
	ret0, _ := ret[0].([]domain.Owner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectOwnersByUserID indicates an expected call of SelectOwnersByUserID.
func (mr *MockIOwnerRepositoryMockRecorder) SelectOwnersByUserID(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectOwnersByUserID", reflect.TypeOf((*MockIOwnerRepository)(nil).SelectOwnersByUserID), userID)
}

// UpdateOwner mocks base method.
func (m *MockIOwnerRepository) UpdateOwner(owner *domain.Owner) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOwner", owner)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOwner indicates an expected call of UpdateOwner.
func (mr *MockIOwnerRepositoryMockRecorder) UpdateOwner(owner interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOwner", reflect.TypeOf((*MockIOwnerRepository)(nil).UpdateOwner), owner)
}
