// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/okadatakuya/my_folder/dev/my_app/badminist/backend/domain/player.go

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
	domain "github.com/takuya-okada-01/badminist-backend/domain"
)

// MockIPlayerRepository is a mock of IPlayerRepository interface.
type MockIPlayerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIPlayerRepositoryMockRecorder
}

// MockIPlayerRepositoryMockRecorder is the mock recorder for MockIPlayerRepository.
type MockIPlayerRepositoryMockRecorder struct {
	mock *MockIPlayerRepository
}

// NewMockIPlayerRepository creates a new mock instance.
func NewMockIPlayerRepository(ctrl *gomock.Controller) *MockIPlayerRepository {
	mock := &MockIPlayerRepository{ctrl: ctrl}
	mock.recorder = &MockIPlayerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPlayerRepository) EXPECT() *MockIPlayerRepositoryMockRecorder {
	return m.recorder
}

// DeletePlayer mocks base method.
func (m *MockIPlayerRepository) DeletePlayer(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePlayer", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePlayer indicates an expected call of DeletePlayer.
func (mr *MockIPlayerRepositoryMockRecorder) DeletePlayer(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePlayer", reflect.TypeOf((*MockIPlayerRepository)(nil).DeletePlayer), id)
}

// InsertPlayer mocks base method.
func (m *MockIPlayerRepository) InsertPlayer(player *domain.Player) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertPlayer", player)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertPlayer indicates an expected call of InsertPlayer.
func (mr *MockIPlayerRepositoryMockRecorder) InsertPlayer(player interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertPlayer", reflect.TypeOf((*MockIPlayerRepository)(nil).InsertPlayer), player)
}

// SelectPlayer mocks base method.
func (m *MockIPlayerRepository) SelectPlayer(id string) (domain.Player, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectPlayer", id)
	ret0, _ := ret[0].(domain.Player)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectPlayer indicates an expected call of SelectPlayer.
func (mr *MockIPlayerRepositoryMockRecorder) SelectPlayer(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectPlayer", reflect.TypeOf((*MockIPlayerRepository)(nil).SelectPlayer), id)
}

// SelectPlayersByCommunityID mocks base method.
func (m *MockIPlayerRepository) SelectPlayersByCommunityID(communityID string) ([]domain.Player, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectPlayersByCommunityID", communityID)
	ret0, _ := ret[0].([]domain.Player)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectPlayersByCommunityID indicates an expected call of SelectPlayersByCommunityID.
func (mr *MockIPlayerRepositoryMockRecorder) SelectPlayersByCommunityID(communityID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectPlayersByCommunityID", reflect.TypeOf((*MockIPlayerRepository)(nil).SelectPlayersByCommunityID), communityID)
}

// UpdatePlayer mocks base method.
func (m *MockIPlayerRepository) UpdatePlayer(player *domain.Player) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePlayer", player)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePlayer indicates an expected call of UpdatePlayer.
func (mr *MockIPlayerRepositoryMockRecorder) UpdatePlayer(player interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePlayer", reflect.TypeOf((*MockIPlayerRepository)(nil).UpdatePlayer), player)
}

// MockIPlayerUseCase is a mock of IPlayerUseCase interface.
type MockIPlayerUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockIPlayerUseCaseMockRecorder
}

// MockIPlayerUseCaseMockRecorder is the mock recorder for MockIPlayerUseCase.
type MockIPlayerUseCaseMockRecorder struct {
	mock *MockIPlayerUseCase
}

// NewMockIPlayerUseCase creates a new mock instance.
func NewMockIPlayerUseCase(ctrl *gomock.Controller) *MockIPlayerUseCase {
	mock := &MockIPlayerUseCase{ctrl: ctrl}
	mock.recorder = &MockIPlayerUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPlayerUseCase) EXPECT() *MockIPlayerUseCaseMockRecorder {
	return m.recorder
}

// DeletePlayer mocks base method.
func (m *MockIPlayerUseCase) DeletePlayer(ctx *gin.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePlayer", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePlayer indicates an expected call of DeletePlayer.
func (mr *MockIPlayerUseCaseMockRecorder) DeletePlayer(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePlayer", reflect.TypeOf((*MockIPlayerUseCase)(nil).DeletePlayer), ctx, id)
}

// InsertPlayer mocks base method.
func (m *MockIPlayerUseCase) InsertPlayer(ctx *gin.Context, player *domain.Player) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertPlayer", ctx, player)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertPlayer indicates an expected call of InsertPlayer.
func (mr *MockIPlayerUseCaseMockRecorder) InsertPlayer(ctx, player interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertPlayer", reflect.TypeOf((*MockIPlayerUseCase)(nil).InsertPlayer), ctx, player)
}

// SelectPlayer mocks base method.
func (m *MockIPlayerUseCase) SelectPlayer(ctx *gin.Context, id string) (domain.Player, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectPlayer", ctx, id)
	ret0, _ := ret[0].(domain.Player)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectPlayer indicates an expected call of SelectPlayer.
func (mr *MockIPlayerUseCaseMockRecorder) SelectPlayer(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectPlayer", reflect.TypeOf((*MockIPlayerUseCase)(nil).SelectPlayer), ctx, id)
}

// SelectPlayersByCommunityID mocks base method.
func (m *MockIPlayerUseCase) SelectPlayersByCommunityID(ctx *gin.Context, communityID string) ([]domain.Player, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectPlayersByCommunityID", ctx, communityID)
	ret0, _ := ret[0].([]domain.Player)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectPlayersByCommunityID indicates an expected call of SelectPlayersByCommunityID.
func (mr *MockIPlayerUseCaseMockRecorder) SelectPlayersByCommunityID(ctx, communityID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectPlayersByCommunityID", reflect.TypeOf((*MockIPlayerUseCase)(nil).SelectPlayersByCommunityID), ctx, communityID)
}

// UpdatePlayer mocks base method.
func (m *MockIPlayerUseCase) UpdatePlayer(ctx *gin.Context, player *domain.Player) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePlayer", ctx, player)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePlayer indicates an expected call of UpdatePlayer.
func (mr *MockIPlayerUseCaseMockRecorder) UpdatePlayer(ctx, player interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePlayer", reflect.TypeOf((*MockIPlayerUseCase)(nil).UpdatePlayer), ctx, player)
}
